# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg484-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/fifonew_synth_1/fifonew.dcp
set_property used_in_implementation false [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/fifonew_synth_1/fifonew.dcp]
add_files -quiet /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/v6_sfifo_15x128_synth_1/v6_sfifo_15x128.dcp
set_property used_in_implementation false [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/v6_sfifo_15x128_synth_1/v6_sfifo_15x128.dcp]
add_files -quiet /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/v6_mBuf_128x72_synth_1/v6_mBuf_128x72.dcp
set_property used_in_implementation false [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/v6_mBuf_128x72_synth_1/v6_mBuf_128x72.dcp]
add_files -quiet /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/pcie_7x_0_synth_1/pcie_7x_0.dcp
set_property used_in_implementation false [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/pcie_7x_0_synth_1/pcie_7x_0.dcp]
read_verilog -library xil_defaultlib {
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/support/pcie_7x_0_pipe_clock.v
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/xise/Emul.v
}
read_vhdl -library xil_defaultlib {
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/pkg_dma.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/FF_tagram64x36.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/DMA_FSM.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/DMA_Calculate.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/Tx_Output_Arbitor.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/tx_Mem_Reader.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_usDMA_Channel.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_MWr_Channel.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_MRd_Channel.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_dsDMA_Channel.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_CplD_Channel.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/RxIn_Delays.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/Interrupts.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/tx_Transact.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/rx_Transact.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/Registers.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/tlpControl.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/adc16bitac701/rtl/FIFO_Wrapper.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/xise/clckinvert.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/cern.git/pcie_axi_trn_bridge.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/support/pcie_7x_0_support.vhd
  /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/imports/rtl/v5pcieDMA.vhd
}
read_xdc /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/constrs_1/imports/cern1.git/pcie_x4_dma.xdc
set_property used_in_implementation false [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/constrs_1/imports/cern1.git/pcie_x4_dma.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property include_dirs {
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/includes
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/avnet_det_lat_16bit/include
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/avnet_det_lat_16bit
} [current_fileset]
set_property webtalk.parent_dir /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.cache/wt [current_project]
set_property parent.project_dir /home/vladimir/TESTDIFFAC/acprv16bit [current_project]
catch { write_hwdef -file v5pcieDMA.hwdef }
synth_design -top v5pcieDMA -part xc7a200tfbg484-1
write_checkpoint v5pcieDMA.dcp
report_utilization -file v5pcieDMA_utilization_synth.rpt -pb v5pcieDMA_utilization_synth.pb
