# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew.xci
# IP: The module: 'fifonew' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew/fifonew_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew/fifonew.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew.xci
# IP: The module: 'fifonew' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew/fifonew_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew/fifonew.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifonew'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
