# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg484-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property include_dirs {
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/includes
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/avnet_det_lat_16bit/include
  /home/vladimir/TESTDIFFAC/adc16bitac701/xise/remote_sources/_/CAG_Link/avnet_det_lat_16bit
} [current_fileset]
set_property webtalk.parent_dir /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.cache/wt [current_project]
set_property parent.project_dir /home/vladimir/TESTDIFFAC/acprv16bit [current_project]
catch { write_hwdef -file fifonew.hwdef }
synth_design -top fifonew -part xc7a200tfbg484-1 -mode out_of_context

rename_ref -prefix_all fifonew_
write_checkpoint -noxdef fifonew.dcp
report_utilization -file fifonew_utilization_synth.rpt -pb fifonew_utilization_synth.pb
if { [catch {
  file copy -force /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.runs/fifonew_synth_1/fifonew.dcp /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew.dcp
  write_verilog -force -mode synth_stub /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_stub.v
  write_vhdl -force -mode synth_stub /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_stub.vhdl
  write_verilog -force -mode funcsim /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_funcsim.v
  write_vhdl -force -mode funcsim /home/vladimir/TESTDIFFAC/acprv16bit/acprv16bit.srcs/sources_1/ip/fifonew/fifonew_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
